'use client';

import { useState, useCallback } from 'react';

// ── Helpers ──────────────────────────────────────────────────────────────────

function escapeLuaString(str) {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
}

function luaValue(val, type) {
  if (type === 'boolean') return val === 'true' ? 'true' : 'false';
  if (type === 'number') return isNaN(Number(val)) ? '0' : val;
  if (type === 'nil') return 'nil';
  // string (default)
  return `"${escapeLuaString(val)}"`;
}

function generateManifest(config, entries) {
  const lines = [];
  lines.push(`-- Generated by Lua Manifest Generator`);
  lines.push(`-- ${new Date().toISOString()}`);
  lines.push('');
  lines.push(`local manifest = {}`);
  lines.push('');

  if (config.name)        lines.push(`manifest.name        = "${escapeLuaString(config.name)}"`);
  if (config.version)     lines.push(`manifest.version     = "${escapeLuaString(config.version)}"`);
  if (config.author)      lines.push(`manifest.author      = "${escapeLuaString(config.author)}"`);
  if (config.description) lines.push(`manifest.description = "${escapeLuaString(config.description)}"`);
  if (config.license)     lines.push(`manifest.license     = "${escapeLuaString(config.license)}"`);
  if (config.homepage)    lines.push(`manifest.homepage    = "${escapeLuaString(config.homepage)}"`);

  if (entries.length > 0) {
    lines.push('');
    lines.push(`manifest.entries = {`);
    entries.forEach((entry, i) => {
      const isLast = i === entries.length - 1;
      if (entry.type === 'section') {
        lines.push(`  -- ${entry.key}`);
        return;
      }
      if (entry.key) {
        const valStr = luaValue(entry.value, entry.type);
        lines.push(`  ${entry.key} = ${valStr}${isLast ? '' : ','}`);
      }
    });
    lines.push(`}`);
  }

  lines.push('');
  lines.push(`return manifest`);
  return lines.join('\n');
}

// ── Sub-components ────────────────────────────────────────────────────────────

function InputField({ label, id, value, onChange, placeholder, type = 'text' }) {
  return (
    <div style={{ marginBottom: '10px' }}>
      <label htmlFor={id} style={{ display: 'block', fontWeight: 600, marginBottom: '4px', fontSize: '13px', color: '#ccc' }}>
        {label}
      </label>
      <input
        id={id}
        type={type}
        value={value}
        onChange={e => onChange(e.target.value)}
        placeholder={placeholder}
        style={{
          width: '100%',
          padding: '7px 10px',
          background: '#1e1e2e',
          border: '1px solid #444',
          borderRadius: '5px',
          color: '#eee',
          fontSize: '13px',
          boxSizing: 'border-box',
        }}
      />
    </div>
  );
}

function EntryRow({ entry, index, onChange, onRemove }) {
  const typeOptions = ['string', 'number', 'boolean', 'nil', 'section'];
  return (
    <tr>
      <td style={{ padding: '4px 6px' }}>
        <input
          value={entry.key}
          onChange={e => onChange(index, 'key', e.target.value)}
          placeholder={entry.type === 'section' ? 'Section label' : 'key'}
          style={inputStyle}
        />
      </td>
      <td style={{ padding: '4px 6px' }}>
        <select
          value={entry.type}
          onChange={e => onChange(index, 'type', e.target.value)}
          style={{ ...inputStyle, cursor: 'pointer' }}
        >
          {typeOptions.map(t => <option key={t} value={t}>{t}</option>)}
        </select>
      </td>
      <td style={{ padding: '4px 6px' }}>
        {entry.type === 'boolean' ? (
          <select value={entry.value} onChange={e => onChange(index, 'value', e.target.value)} style={{ ...inputStyle, cursor: 'pointer' }}>
            <option value="true">true</option>
            <option value="false">false</option>
          </select>
        ) : entry.type === 'nil' || entry.type === 'section' ? (
          <input value="" disabled style={{ ...inputStyle, opacity: 0.4 }} placeholder="–" />
        ) : (
          <input
            value={entry.value}
            onChange={e => onChange(index, 'value', e.target.value)}
            placeholder="value"
            style={inputStyle}
          />
        )}
      </td>
      <td style={{ padding: '4px 6px', textAlign: 'center' }}>
        <button onClick={() => onRemove(index)} style={btnDangerStyle} title="Remove">✕</button>
      </td>
    </tr>
  );
}

const inputStyle = {
  width: '100%',
  padding: '6px 8px',
  background: '#1e1e2e',
  border: '1px solid #444',
  borderRadius: '4px',
  color: '#eee',
  fontSize: '13px',
  boxSizing: 'border-box',
};

const btnDangerStyle = {
  background: '#7f1d1d',
  color: '#fca5a5',
  border: 'none',
  borderRadius: '4px',
  padding: '4px 10px',
  cursor: 'pointer',
  fontSize: '13px',
};

// ── Main Page ─────────────────────────────────────────────────────────────────

const defaultConfig = {
  name: '',
  version: '1.0.0',
  author: '',
  description: '',
  license: 'MIT',
  homepage: '',
};

const defaultEntry = () => ({ key: '', value: '', type: 'string' });

export default function LuaManifestPage() {
  const [config, setConfig] = useState(defaultConfig);
  const [entries, setEntries] = useState([defaultEntry()]);
  const [output, setOutput] = useState('');
  const [copied, setCopied] = useState(false);

  const setConfigField = (field) => (val) => setConfig(prev => ({ ...prev, [field]: val }));

  const handleEntryChange = useCallback((index, field, value) => {
    setEntries(prev => {
      const next = [...prev];
      next[index] = { ...next[index], [field]: value };
      // Reset value when type changes
      if (field === 'type') {
        if (value === 'boolean') next[index].value = 'true';
        else if (value === 'nil' || value === 'section') next[index].value = '';
        else next[index].value = '';
      }
      return next;
    });
  }, []);

  const addEntry = () => setEntries(prev => [...prev, defaultEntry()]);
  const addSection = () => setEntries(prev => [...prev, { key: 'Section Name', value: '', type: 'section' }]);
  const removeEntry = (index) => setEntries(prev => prev.filter((_, i) => i !== index));

  const handleGenerate = () => {
    const lua = generateManifest(config, entries);
    setOutput(lua);
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(output).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    const blob = new Blob([output], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${config.name || 'manifest'}.lua`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleReset = () => {
    setConfig(defaultConfig);
    setEntries([defaultEntry()]);
    setOutput('');
  };

  return (
    <div style={{ minHeight: '100vh', background: '#0f0f1a', color: '#eee', fontFamily: 'monospace', padding: '30px 20px' }}>
      <div style={{ maxWidth: '900px', margin: '0 auto' }}>

        {/* Header */}
        <div style={{ marginBottom: '24px' }}>
          <h1 style={{ fontSize: '26px', fontWeight: 700, color: '#a78bfa', margin: 0 }}>🌙 Lua Manifest Generator</h1>
          <p style={{ color: '#888', marginTop: '6px', fontSize: '13px' }}>
            Generate a <code style={{ color: '#c084fc' }}>manifest.lua</code> file for your Lua project or mod.
          </p>
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px' }}>
          {/* Left: Config */}
          <div>
            <section style={sectionStyle}>
              <h2 style={sectionTitleStyle}>📦 Metadata</h2>
              <InputField label="Name" id="name" value={config.name} onChange={setConfigField('name')} placeholder="my-lua-mod" />
              <InputField label="Version" id="version" value={config.version} onChange={setConfigField('version')} placeholder="1.0.0" />
              <InputField label="Author" id="author" value={config.author} onChange={setConfigField('author')} placeholder="Your Name" />
              <InputField label="Description" id="description" value={config.description} onChange={setConfigField('description')} placeholder="Short description" />
              <InputField label="License" id="license" value={config.license} onChange={setConfigField('license')} placeholder="MIT" />
              <InputField label="Homepage / URL" id="homepage" value={config.homepage} onChange={setConfigField('homepage')} placeholder="https://github.com/..." />
            </section>

            {/* Entries */}
            <section style={sectionStyle}>
              <h2 style={sectionTitleStyle}>📋 Custom Entries</h2>
              <div style={{ overflowX: 'auto' }}>
                <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                  <thead>
                    <tr style={{ color: '#aaa', borderBottom: '1px solid #333' }}>
                      <th style={{ padding: '4px 6px', textAlign: 'left' }}>Key</th>
                      <th style={{ padding: '4px 6px', textAlign: 'left' }}>Type</th>
                      <th style={{ padding: '4px 6px', textAlign: 'left' }}>Value</th>
                      <th style={{ padding: '4px 6px' }}></th>
                    </tr>
                  </thead>
                  <tbody>
                    {entries.map((entry, i) => (
                      <EntryRow key={i} entry={entry} index={i} onChange={handleEntryChange} onRemove={removeEntry} />
                    ))}
                  </tbody>
                </table>
              </div>
              <div style={{ display: 'flex', gap: '8px', marginTop: '10px' }}>
                <button onClick={addEntry} style={btnStyle}>+ Add Entry</button>
                <button onClick={addSection} style={{ ...btnStyle, background: '#1e3a4a', color: '#7dd3fc' }}>+ Section Comment</button>
              </div>
            </section>

            {/* Actions */}
            <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
              <button onClick={handleGenerate} style={{ ...btnStyle, background: '#5b21b6', fontSize: '14px', padding: '9px 20px' }}>
                ⚙️ Generate
              </button>
              <button onClick={handleReset} style={{ ...btnStyle, background: '#374151', fontSize: '14px', padding: '9px 20px' }}>
                🔄 Reset
              </button>
            </div>
          </div>

          {/* Right: Output */}
          <div>
            <section style={{ ...sectionStyle, height: 'fit-content' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '10px' }}>
                <h2 style={{ ...sectionTitleStyle, margin: 0 }}>📄 Output</h2>
                {output && (
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <button onClick={handleCopy} style={{ ...btnStyle, fontSize: '12px', padding: '5px 12px' }}>
                      {copied ? '✅ Copied!' : '📋 Copy'}
                    </button>
                    <button onClick={handleDownload} style={{ ...btnStyle, fontSize: '12px', padding: '5px 12px', background: '#14532d', color: '#86efac' }}>
                      ⬇️ Download
                    </button>
                  </div>
                )}
              </div>
              <textarea
                readOnly
                value={output || '-- Click "Generate" to see output here'}
                style={{
                  width: '100%',
                  minHeight: '450px',
                  background: '#0d0d1a',
                  border: '1px solid #333',
                  borderRadius: '6px',
                  color: output ? '#a3e635' : '#555',
                  fontFamily: '"Courier New", monospace',
                  fontSize: '13px',
                  padding: '12px',
                  resize: 'vertical',
                  boxSizing: 'border-box',
                  lineHeight: '1.6',
                }}
              />
            </section>

            {/* Quick Templates */}
            <section style={sectionStyle}>
              <h2 style={sectionTitleStyle}>🚀 Quick Templates</h2>
              <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                <button onClick={() => applyTemplate('mod', setConfig, setEntries)} style={{ ...btnStyle, fontSize: '12px' }}>
                  🎮 Game Mod
                </button>
                <button onClick={() => applyTemplate('lib', setConfig, setEntries)} style={{ ...btnStyle, fontSize: '12px' }}>
                  📚 Library
                </button>
                <button onClick={() => applyTemplate('plugin', setConfig, setEntries)} style={{ ...btnStyle, fontSize: '12px' }}>
                  🔌 Plugin
                </button>
              </div>
            </section>
          </div>
        </div>
      </div>
    </div>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────

const sectionStyle = {
  background: '#161625',
  border: '1px solid #2a2a3e',
  borderRadius: '8px',
  padding: '16px',
  marginBottom: '16px',
};

const sectionTitleStyle = {
  fontSize: '14px',
  fontWeight: 700,
  color: '#c084fc',
  marginTop: 0,
  marginBottom: '12px',
};

const btnStyle = {
  background: '#3b0764',
  color: '#e9d5ff',
  border: 'none',
  borderRadius: '5px',
  padding: '6px 14px',
  cursor: 'pointer',
  fontSize: '13px',
};

// ── Templates ─────────────────────────────────────────────────────────────────

function applyTemplate(tpl, setConfig, setEntries) {
  if (tpl === 'mod') {
    setConfig({
      name: 'my-game-mod',
      version: '1.0.0',
      author: 'YourName',
      description: 'A game modification.',
      license: 'MIT',
      homepage: '',
    });
    setEntries([
      { key: 'game_version', value: '1.0', type: 'string' },
      { key: 'load_priority', value: '10', type: 'number' },
      { key: 'enabled', value: 'true', type: 'boolean' },
      { key: 'debug_mode', value: 'false', type: 'boolean' },
      { key: 'required_mods', value: 'none', type: 'string' },
    ]);
  } else if (tpl === 'lib') {
    setConfig({
      name: 'my-lua-lib',
      version: '0.1.0',
      author: 'YourName',
      description: 'A Lua utility library.',
      license: 'MIT',
      homepage: 'https://github.com/yourname/my-lua-lib',
    });
    setEntries([
      { key: 'lua_version', value: '5.4', type: 'string' },
      { key: 'is_standalone', value: 'true', type: 'boolean' },
      { key: 'entry_point', value: 'init.lua', type: 'string' },
    ]);
  } else if (tpl === 'plugin') {
    setConfig({
      name: 'my-plugin',
      version: '2.0.0',
      author: 'YourName',
      description: 'A plugin for an application.',
      license: 'Apache-2.0',
      homepage: '',
    });
    setEntries([
      { key: 'plugin_type', value: 'extension', type: 'string' },
      { key: 'api_version', value: '3', type: 'number' },
      { key: 'autoload', value: 'true', type: 'boolean' },
      { key: 'priority', value: '100', type: 'number' },
    ]);
  }
}
